apiVersion: v2
name: compose-deployer
description: A Helm chart that uses the Compose spec as its values to create Kubernetes resources

type: application
version: 0.2.0
appVersion: 1.16.0
maintainers:
  - name: mikesir87
    email: mikesir87@gmail.com
    url: https://mikesir87.io
